name: Build Docker Image & Publish

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Github Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: raiyansarker/opengraph-generator/opengraph-generator
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: server
